In [4]:
from src import data
import pandas as pd
metaloader = data.MetadataLoader("tests/data/catalog-test.pkl")
meta = metaloader.load(data.Station.BND, "8bit", night_time=False)

données_traitées = pd.DataFrame.from_dict(next(meta).__dict__, orient="index").transpose()
for ligne in meta:
    données_traitées = données_traitées.append(pd.DataFrame.from_dict(ligne.__dict__, orient="index").transpose())

tests/data/catalog-test.pkl

In [6]:
données_traitées.to_excel("blah.xlsx")

In [5]:
données_traitées

,image_path,image_compression,image_offset,datetime,latitude,longitude,altitude,target_ghi,target_ghi_1h,target_ghi_3h,target_ghi_6h,target_cloudiness,target_cloudiness_1h,target_cloudiness_3h,target_cloudiness_6h
0,/project/cq-training-1/project1/data/hdf5v7_8b...,8bit,22,2010-01-01 13:30:00,40.0519,-88.3731,230,5.01333,130.973,412.907,395.3,variable,clear,clear,slightly cloudy
0,/project/cq-training-1/project1/data/hdf5v7_8b...,8bit,23,2010-01-01 13:45:00,40.0519,-88.3731,230,15.9,172.113,435.047,381.393,variable,clear,clear,variable
0,/project/cq-training-1/project1/data/hdf5v7_8b...,8bit,24,2010-01-01 14:00:00,40.0519,-88.3731,230,29.1067,211.873,452.687,361.38,variable,clear,clear,slightly cloudy
0,/project/cq-training-1/project1/data/hdf5v7_8b...,8bit,25,2010-01-01 14:15:00,40.0519,-88.3731,230,91.8267,251.233,472.98,373.753,slightly cloudy,clear,clear,variable
0,/project/cq-training-1/project1/data/hdf5v7_8b...,8bit,26,2010-01-01 14:30:00,40.0519,-88.3731,230,130.973,288.813,466.573,251.82,clear,clear,slightly cloudy,variable
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,/project/cq-training-1/project1/data/hdf5v7_8b...,8bit,38,2011-11-22 17:30:00,40.0519,-88.3731,230,35.62,None,None,None,cloudy,None,None,None
0,/project/cq-training-1/project1/data/hdf5v7_8b...,8bit,60,2010-08-15 23:00:00,40.0519,-88.3731,230,304.24,None,None,None,clear,None,None,None
0,/project/cq-training-1/project1/data/hdf5v7_8b...,8bit,44,2010-05-11 19:00:00,40.0519,-88.3731,230,722.44,None,None,None,variable,None,None,None
0,/project/cq-training-1/project1/data/hdf5v7_8b...,8bit,25,2013-02-15 14:15:00,40.0519,-88.3731,230,57.3067,None,None,None,cloudy,None,None,None
0,/project/cq-training-1/project1/data/hdf5v7_8b...,8bit,39,2011-02-08 17:45:00,40.0519,-88.3731,230,673.807,None,None,None,clear,None,None,None

In [31]:
#catalog

In [32]:
catalog[catalog["BND_DAYTIME"]==True]

,ncdf_path,hdf5_8bit_path,hdf5_8bit_offset,hdf5_16bit_path,hdf5_16bit_offset,BND_DAYTIME,BND_CLEARSKY_GHI,BND_CLOUDINESS,BND_GHI,TBL_DAYTIME,...,GWN_CLOUDINESS,GWN_GHI,PSU_DAYTIME,PSU_CLEARSKY_GHI,PSU_CLOUDINESS,PSU_GHI,SXF_DAYTIME,SXF_CLEARSKY_GHI,SXF_CLOUDINESS,SXF_GHI
iso-datetime,,,,,,,,,,,,,,,,,,,,,
2010-01-01 13:30:00,nan,/project/cq-training-1/project1/data/hdf5v7_8b...,22,/project/cq-training-1/project1/data/hdf5v5_16...,22,1,5.523046,variable,5.013333,0,...,variable,11.500000,1,83.959541,cloudy,35.786667,0,0.000000,night,-3.440000
2010-01-01 13:45:00,nan,/project/cq-training-1/project1/data/hdf5v7_8b...,23,/project/cq-training-1/project1/data/hdf5v5_16...,23,1,27.658028,variable,15.900000,0,...,slightly cloudy,24.666667,1,122.956825,cloudy,39.773333,0,0.000000,night,-3.080000
2010-01-01 14:00:00,nan,/project/cq-training-1/project1/data/hdf5v7_8b...,24,/project/cq-training-1/project1/data/hdf5v5_16...,24,1,61.184611,variable,29.106667,0,...,cloudy,43.620000,1,162.167931,cloudy,32.166667,0,0.000000,night,-1.200000
2010-01-01 14:15:00,nan,/project/cq-training-1/project1/data/hdf5v7_8b...,25,/project/cq-training-1/project1/data/hdf5v5_16...,25,1,99.551959,slightly cloudy,91.826667,0,...,cloudy,61.220000,1,200.404908,cloudy,36.953333,1,3.584734,cloudy,4.586667
2010-01-01 14:30:00,nan,/project/cq-training-1/project1/data/hdf5v7_8b...,26,/project/cq-training-1/project1/data/hdf5v5_16...,26,1,139.346794,clear,130.973333,1,...,variable,97.013333,1,236.951941,cloudy,48.520000,1,20.124553,variable,17.113333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2011-11-22 17:30:00,/project/cq-training-1/project1/data/netcdf/GO...,/project/cq-training-1/project1/data/hdf5v7_8b...,38,/project/cq-training-1/project1/data/hdf5v5_16...,38,1,491.948725,cloudy,35.620000,1,...,cloudy,47.093333,1,470.043666,cloudy,39.246667,1,409.632339,cloudy,132.220000
2010-08-15 23:00:00,/project/cq-training-1/project1/data/netcdf/GO...,/project/cq-training-1/project1/data/hdf5v7_8b...,60,/project/cq-training-1/project1/data/hdf5v5_16...,60,1,245.150706,clear,304.240000,1,...,clear,312.386667,1,111.478788,variable,116.246667,1,363.082551,variable,302.820000
2010-05-11 19:00:00,/project/cq-training-1/project1/data/netcdf/GO...,/project/cq-training-1/project1/data/hdf5v7_8b...,44,/project/cq-training-1/project1/data/hdf5v5_16...,44,1,863.057654,variable,722.440000,1,...,variable,871.813333,1,829.535316,cloudy,94.206667,1,897.140557,cloudy,204.586667
2013-02-15 14:15:00,/project/cq-training-1/project1/data/netcdf/GO...,/project/cq-training-1/project1/data/hdf5v7_8b...,25,/project/cq-training-1/project1/data/hdf5v5_16...,25,1,207.685968,cloudy,57.306667,1,...,variable,244.513333,1,338.500992,cloudy,120.926667,1,73.395188,slightly cloudy,44.460000
2011-02-08 17:45:00,/project/cq-training-1/project1/data/netcdf/GO...,/project/cq-training-1/project1/data/hdf5v7_8b...,39,/project/cq-training-1/project1/data/hdf5v5_16...,39,1,582.737409,clear,673.806667,1,...,clear,685.386667,1,588.524474,variable,321.993333,1,495.338486,slightly cloudy,609.433333

In [3]:
import pickle
catalog = pickle.load(open("tests/data/catalog-test.pkl","rb"))

In [6]:
catalog[['hdf5_8bit_offset', 'hdf5_16bit_offset']]

                    BND_CLOUDINESS     BND_GHI
iso-datetime
2010-01-01 00:00:00          night   -4.100000
2010-01-01 00:15:00          night   -4.100000
2010-01-01 00:30:00          night   -4.100000
2010-01-01 00:45:00          night   -4.100000
2010-01-01 01:00:00          night   -4.100000
...                            ...         ...
2010-08-15 23:00:00          clear  304.240000
2010-05-11 19:00:00       variable  722.440000
2013-02-15 14:15:00         cloudy   57.306667
2010-03-03 01:00:00          night   -3.500000
2011-02-08 17:45:00          clear  673.806667

[2100 rows x 2 columns]